### ISSUE TITLE
Create ClassLoader

### ISSUE THREAD

**Issue by fourhundredfour** [fourhundredfour/doctrine-lombok#3]
The ClassLoader must parse a Filepath to a valid[ PSR-4](https://www.php-fig.org/psr/psr-4/) classname.

Ensure that:
* Subdirectories should be parsed too (Consider to implement a maximum)
* Only to parse files with .php as extension

https://github.com/fourhundredfour/doctrine-lombok/blob/master/src/ClassLoader.php

**Comment by georgleber** [comment]
Added a PR #4
